package main.java.com.homeparty.otus;

/**
 * Created by Gleb Skalatsky on 03-Apr-17.
 */
public class Starter {
    public static void main(String[] args) {
        System.out.println("Generated by Maven. Woohoo!");
    }
}
